print('======Desafio2======')
print('Crie o script python que leia o dia, o mês, o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.')
dia = input('Qual dia você nasceu ?')
mes = input('Qual mês você nasceu?')
ano = input('Qual ano você nasceu?')
print('Você nasceu no dia', dia, 'de' , mes, 'de' , ano ,'. Correto?')
